version: '3.8'
services:
  c-container-staging:
    image: mohammadnowresideh1997/c-container-staging
    container_name: c-container-staging
    restart: always
    ports:
      - 3004:3004
    networks:
      - services_app-network

networks:
  services_app-network:
    external: true
