version: '3.8'
services:
  c-container-staging:
    image: ${DOCKER_USERNAME}/c-container-staging
    env_file:
      - /root/config/c-container-staging.env.txt
    container_name: c-container-staging
    restart: always
    ports:
      - ${PORT}:${PORT}
    networks:
      - services_app-network

networks:
  services_app-network:
    external: true
