name: Build

on:
  push:
    branches:
      - integration

jobs:
  build:
    name: Building the bs.c-container app
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Installing the node_modules packages
        run: npm install
